services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aquasense-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - aquasense-sqlserver-data:/var/opt/mssql
    networks:
      - aquasense-network

  api:
    build:
      context: ./AquaSenseAPI
      dockerfile: Dockerfile
    container_name: aquasense-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=AquaSenseDB;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=True"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - aquasense-network

volumes:
  aquasense-sqlserver-data:

networks:
  aquasense-network:
    driver: bridge